### ISSUE TITLE
Add telegraf check for SSL certificate

### ISSUE THREAD

**Issue by billglick** [ncsa/puppet-profile_globus#4]
Need to add a x509_cert check for the SSL certificate(s) used by Globus.

Should be something like the following added in a new file under `/etc/telegraf/telegraf.d`:
```
[[inputs.x509_cert]]
  sources = [
    "file:///path/to/*.pem"
  ]
  interval = "3h"
```

**Comment by srstevens** [comment]
As we discussed, with GCSv5, Globus moved to automatically configuring Let's Encrypt, so we shouldn't need to monitor certificates anymore.
